package com.enterprise.ems.config;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

@Configuration
public class DatabaseInitializer {

    @Autowired
    private DataSource dataSource;

    public void initializeDatabase() {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {

            // Check if the table 'employees' exists
            String checkTableQuery = "SELECT table_name FROM all_tables WHERE table_name = 'EMPLOYEES'";
            ResultSet rs = statement.executeQuery(checkTableQuery);

            // If the table does not exist, create it
            if (!rs.next()) {
                String createTableQuery = "CREATE TABLE employees (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "first_name VARCHAR2(50) NOT NULL, " +
                        "last_name VARCHAR2(50) NOT NULL, " +
                        "email VARCHAR2(100) UNIQUE NOT NULL" +
                        ")";
                statement.executeUpdate(createTableQuery);
                System.out.println("Table 'employees' created.");
            } else {
                System.out.println("Table 'employees' already exists.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
